# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1bb1iI9-p8aVFZ96lQ17jc7pIDEDquzzw
"""

!pip install -q streamlit

!pip install streamlit openai googletrans==4.0.0-rc1

import openai
import streamlit as st
from googletrans import Translator

# OpenAI API Key (replace with your own)
openai.api_key = "your-api-key-here"

st.title("🌍 AI Math Tutor Chatbot")
st.write("Ask me a math question! I'll explain it step by step.")

# Select a language
languages = {"English": "en", "Spanish": "es", "French": "fr", "German": "de", "Chinese": "zh-cn"}
selected_language = st.selectbox("Choose your language:", list(languages.keys()))

# Get user input
user_input = st.text_input("Type your math question:")

def get_math_explanation(question):
    response = openai.ChatCompletion.create(
        model="gpt-4",
        messages=[
            {"role": "system", "content": "You are a friendly math tutor who explains concepts step by step."},
            {"role": "user", "content": question}
        ]
    )
    return response["choices"][0]["message"]["content"]

def translate_text(text, target_language):
    translator = Translator()
    return translator.translate(text, dest=target_language).text

if user_input:
    explanation = get_math_explanation(user_input)
    translated_explanation = translate_text(explanation, languages[selected_language])
    st.write(translated_explanation)

import openai
import streamlit as st
from googletrans import Translator


# Store points in session state
if "points" not in st.session_state:
    st.session_state.points = 0

st.title("🌍 AI Math Tutor Chatbot 🎓")
st.write("Ask me a math question! Earn points for correct answers.")

# Select a language
languages = {
    "English": "en",
    "Spanish": "es",
    "French": "fr",
    "German": "de",
    "Chinese": "zh-cn",
    "Arabic": "ar",
    "Hindi": "hi",
    "Urdu": "ur"
}
selected_language = st.selectbox("Choose your language:", list(languages.keys()))

# Get user input
user_input = st.text_input("Type your math question:")

def get_math_explanation(question):
    response = openai.ChatCompletion.create(
        model="gpt-4",
        messages=[
            {"role": "system", "content": "You are a fun math tutor who explains concepts step by step."},
            {"role": "user", "content": question}
        ]
    )
    return response["choices"][0]["message"]["content"]

def translate_text(text, target_language):
    translator = Translator()
    return translator.translate(text, dest=target_language).text

if user_input:
    explanation = get_math_explanation(user_input)
    translated_explanation = translate_text(explanation, languages[selected_language])
    st.write(translated_explanation)

    # Add points and display score
    st.session_state.points += 10
    st.success(f"🎉 You earned 10 points! Total: {st.session_state.points} points")

import random

st.subheader("🎮 Math Mini-Game: Quick Multiply!")

if "question" not in st.session_state:
    num1 = random.randint(1, 10)
    num2 = random.randint(1, 10)
    st.session_state.question = f"{num1} × {num2}"
    st.session_state.answer = num1 * num2

st.write(f"🧮 Solve: {st.session_state.question}")

game_answer = st.text_input("Your Answer:")
if game_answer:
    if int(game_answer) == st.session_state.answer:
        st.session_state.points += 20
        st.success(f"✅ Correct! You earned 20 points. Total: {st.session_state.points} points")
        st.session_state.pop("question")  # Reset the question
    else:
        st.error("❌ Incorrect! Try again.")

with open("requirements.txt", "w") as file:
    file.write("openai\n")
    file.write("streamlit\n")
    file.write("googletrans==4.0.0-rc1\n")

with open("app.py", "w") as file:
    file.write(code)

from google.colab import files
files.download("requirements.txt")